# Generated by Django 5.1.2 on 2025-11-30 20:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('location', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this need expires', null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('contact_preference', models.CharField(choices=[('message', 'In-app message'), ('email', 'Email'), ('phone', 'Phone'), ('any', 'Any method')], default='message', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='needs', to='core.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NeedInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Message expressing interest in helping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='core.need')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Handshake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When the exchange actually started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the exchange was completed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the handshake')),
                ('user1', models.ForeignKey(help_text='First user in the handshake (offer/need creator)', on_delete=django.db.models.deletion.CASCADE, related_name='handshakes_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(help_text='Second user in the handshake (interested/helping user)', on_delete=django.db.models.deletion.CASCADE, related_name='handshakes_as_user2', to=settings.AUTH_USER_MODEL)),
                ('need_interest', models.OneToOneField(blank=True, help_text='The need interest this handshake is based on', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handshake', to='core.needinterest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('location', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('fulfilled', 'Fulfilled'), ('paused', 'Paused'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this offer expires', null=True)),
                ('is_reciprocal', models.BooleanField(default=True, help_text='User is open to receiving help in return')),
                ('contact_preference', models.CharField(choices=[('message', 'In-app message'), ('email', 'Email'), ('phone', 'Phone'), ('any', 'Any method')], default='message', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='offers', to='core.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Message expressing interest')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='core.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handshake', models.ForeignKey(blank=True, help_text='Message within an active handshake', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.handshake')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('need_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.needinterest')),
                ('offer_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.offerinterest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='handshake',
            name='offer_interest',
            field=models.OneToOneField(blank=True, help_text='The offer interest this handshake is based on', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handshake', to='core.offerinterest'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself', max_length=500)),
                ('location', models.CharField(blank=True, help_text='Your general location', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map', max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Community verification status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='needinterest',
            index=models.Index(fields=['status', '-created_at'], name='core_needin_status_d905a0_idx'),
        ),
        migrations.AddIndex(
            model_name='needinterest',
            index=models.Index(fields=['need', 'user'], name='core_needin_need_id_cc3ed8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='needinterest',
            unique_together={('need', 'user')},
        ),
        migrations.AddIndex(
            model_name='offerinterest',
            index=models.Index(fields=['status', '-created_at'], name='core_offeri_status_c16ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='offerinterest',
            index=models.Index(fields=['offer', 'user'], name='core_offeri_offer_i_180300_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerinterest',
            unique_together={('offer', 'user')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'recipient', '-created_at'], name='core_messag_sender__9e7f42_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', '-created_at'], name='core_messag_is_read_54a96e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['handshake', '-created_at'], name='core_messag_handsha_852d05_idx'),
        ),
        migrations.AddIndex(
            model_name='handshake',
            index=models.Index(fields=['status', '-created_at'], name='core_handsh_status_cc9331_idx'),
        ),
        migrations.AddIndex(
            model_name='handshake',
            index=models.Index(fields=['user1', 'user2'], name='core_handsh_user1_i_314a64_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', '-created_at'], name='core_offer_status_d71277_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['latitude', 'longitude'], name='core_offer_latitud_7f1795_idx'),
        ),
        migrations.AddIndex(
            model_name='need',
            index=models.Index(fields=['status', '-created_at'], name='core_need_status_417cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='need',
            index=models.Index(fields=['is_urgent', '-created_at'], name='core_need_is_urge_a8e067_idx'),
        ),
        migrations.AddIndex(
            model_name='need',
            index=models.Index(fields=['latitude', 'longitude'], name='core_need_latitud_4fddce_idx'),
        ),
    ]
