# Generated by Django 5.1.2 on 2025-12-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='need',
            name='core_need_is_urge_a8e067_idx',
        ),
        migrations.RemoveField(
            model_name='need',
            name='is_urgent',
        ),
        migrations.AddField(
            model_name='offer',
            name='duration',
            field=models.CharField(blank=True, help_text="Duration of the offer (e.g., '1 Hour', '2 Hours')", max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='frequency',
            field=models.CharField(blank=True, choices=[('one-time', 'One-time'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('on-demand', 'On-demand')], help_text='How often this offer is available', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the offer', null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='max_people',
            field=models.IntegerField(blank=True, help_text='Maximum number of people', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_people',
            field=models.IntegerField(blank=True, help_text='Minimum number of people', null=True),
        ),
    ]
