# Generated by Django 5.1.2 on 2025-12-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_need_core_need_is_urge_a8e067_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the need', null=True, upload_to='needs/'),
        ),
    ]
