# Generated by Django 5.1.2 on 2025-12-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_need_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('newbee', 'New Bee'), ('worker', 'Worker Bee'), ('queen', 'Queen Bee'), ('drone', 'Drone')], default='newbee', help_text='User rank badge', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reputation_score',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='User reputation score', max_digits=5),
        ),
    ]
