# Generated by Django 5.1.2 on 2025-12-13 21:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_is_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='handshake',
            name='honey_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount of honey provisioned for this handshake', max_digits=10),
        ),
        migrations.AddField(
            model_name='need',
            name='duration',
            field=models.CharField(blank=True, help_text="Duration of the need (e.g., '1 Hour', '2 Hours')", max_length=50),
        ),
        migrations.CreateModel(
            name='HoneyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_honey', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total honey balance (usable + provisioned)', max_digits=10)),
                ('provisioned_honey', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Honey temporarily reserved in active handshakes', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='honey_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
