# Generated by Django 5.1.2 on 2025-12-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_handshake_honey_amount_need_duration_honeybalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handshake',
            name='honey_amount',
            field=models.IntegerField(default=0, help_text='Amount of honey provisioned for this handshake (in hours)'),
        ),
        migrations.AlterField(
            model_name='honeybalance',
            name='provisioned_honey',
            field=models.IntegerField(default=0, help_text='Honey temporarily reserved in active handshakes (in hours)'),
        ),
        migrations.AlterField(
            model_name='honeybalance',
            name='total_honey',
            field=models.IntegerField(default=0, help_text='Total honey balance (usable + provisioned) in hours'),
        ),
    ]
