"""
Django settings for appsite project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2+g-mi6*cqlyfgk7oy-+1x-3w6bwbrs)k2z#&5_g&-cp$kmi0e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'django-app-494208442673.europe-west1.run.app']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'core',  # The Hive core models
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://django-app-494208442673.europe-west1.run.app",
    "https://react-frontend-494208442673.europe-west1.run.app",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://django-app-494208442673.europe-west1.run.app",
    "https://react-frontend-494208442673.europe-west1.run.app",
]

CORS_ALLOW_CREDENTIALS = True
# Expose headers that might be needed
CORS_EXPOSE_HEADERS = ['Content-Type', 'Authorization']
# Allow all headers in requests
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# Ensure session cookie is accessible across origins
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 86400  # 24 hours
# Use database-backed sessions for reliability
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

ROOT_URLCONF = 'appsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'appsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Database configuration
# Priority: Environment variables > Cloud Run > Docker Compose > Local SQLite

# Check if running in Cloud Run (Cloud SQL socket exists)
CLOUD_SQL_SOCKET = "/cloudsql/dicleshive:europe-west1:django-postgres"
is_cloud_run = os.path.exists(CLOUD_SQL_SOCKET)

# Check if running in Docker Compose (db host exists)
is_docker = os.path.exists("/.dockerenv") or os.environ.get("DOCKER_CONTAINER") == "true"

# Use environment variable to force database type, or auto-detect
USE_POSTGRES = os.environ.get("USE_POSTGRES", "").lower() == "true"
USE_SQLITE = os.environ.get("USE_SQLITE", "").lower() == "true"

if is_cloud_run:
    # Production: Use Cloud SQL Unix socket
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": CLOUD_SQL_SOCKET,
            "PORT": os.environ.get("DB_PORT", "5432"),
            "NAME": os.environ.get("DB_NAME", "django_db"),
            "USER": os.environ.get("DB_USER", "django_user"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "django_pass"),
        }
    }
elif is_docker or USE_POSTGRES:
    # Docker Compose or forced PostgreSQL: Use PostgreSQL with db host
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": os.environ.get("DB_HOST", "db"),
            "PORT": os.environ.get("DB_PORT", "5432"),
            "NAME": os.environ.get("DB_NAME", "django_db"),
            "USER": os.environ.get("DB_USER", "django_user"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "django_pass"),
        }
    }
elif USE_SQLITE or os.environ.get("DB_ENGINE") == "sqlite3":
    # Forced SQLite or explicit SQLite setting
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # Local development (default): Use SQLite for easy setup
    # Set USE_POSTGRES=true to use PostgreSQL instead
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Cookie settings - adjust for local development
# In production/Cloud Run, these should be True/None
# For local development, set to False/Lax
IS_LOCAL_DEV = not is_cloud_run and not is_docker

SESSION_COOKIE_SAMESITE = "Lax" if IS_LOCAL_DEV else "None"
CSRF_COOKIE_SAMESITE = "Lax" if IS_LOCAL_DEV else "None"
SESSION_COOKIE_SECURE = False if IS_LOCAL_DEV else True
CSRF_COOKIE_SECURE = False if IS_LOCAL_DEV else True

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploaded files)
# https://docs.djangoproject.com/en/5.1/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Cache configuration for token storage
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}
